services:
  postgres:
    image: postgres:latest
    container_name: tournamate-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: SDfghjkl25!
      POSTGRES_USER: myuser
      POSTGRES_DB: tournamate
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
